import { interestChoices } from "@/lib/validation";

export type PublicLanguage = "fr" | "en";

export const publicCopy = {
  fr: {
    heroTitle: "Continuons la conversation.",
    heroCopy: "Laissez-nous vos coordonnées et l’équipe KZero communiquera avec vous après la conférence.",
    stayInTouch: "Restons en contact",
    yourDetails: "Vos coordonnées",
    required: "Obligatoire",
    optional: "Facultatif",
    fullName: "Nom complet",
    fullNamePlaceholder: "Alex Morgan",
    company: "Entreprise",
    companyPlaceholder: "Nom de l’entreprise",
    workEmail: "Courriel professionnel",
    emailPlaceholder: "alex@entreprise.com",
    jobTitle: "Poste",
    phone: "Téléphone",
    endpoints: "Nombre approximatif de terminaux",
    passwordManager: "Gestionnaire de mots de passe actuel",
    identityProvider: "Fournisseur SSO ou d’identité actuel",
    interests: "Qu’est-ce qui vous intéresse le plus?",
    chooseAny: "Choisissez toutes les réponses pertinentes",
    interestLabels: {
      "Passwordless authentication": "Authentification sans mot de passe",
      "KZero Vault": "KZero Vault",
      "MSP partnership": "Partenariat MSP",
      Demo: "Démonstration",
      Other: "Autre"
    } satisfies Record<(typeof interestChoices)[number], string>,
    comments: "Commentaires ou notes",
    commentsPlaceholder: "Y a-t-il autre chose que vous aimeriez communiquer à l’équipe KZero?",
    demoRequest: "J’aimerais réserver une démonstration de KZero après la conférence.",
    demoFollowUp: "L’équipe communiquera avec vous pour convenir d’un moment.",
    submit: "Envoyer mes coordonnées",
    submitting: "Enregistrement sécurisé…",
    submitError: "Nous n’avons pas pu enregistrer vos coordonnées pour le moment.",
    retry: "Vos réponses sont toujours ici — veuillez réessayer.",
    privacy: "En soumettant ce formulaire, vous acceptez que KZero utilise ces renseignements pour donner suite à votre demande. Aucun consentement marketing n’est demandé et aucune option facultative n’est présélectionnée.",
    received: "Coordonnées reçues",
    thankYou: "Merci de votre visite.",
    confirmation: "L’équipe KZero communiquera avec vous après la conférence. Au plaisir de poursuivre la conversation."
  },
  en: {
    heroTitle: "Let’s keep the conversation going.",
    heroCopy: "Leave your details and the KZero team will follow up after the conference.",
    stayInTouch: "Stay in touch",
    yourDetails: "Your details",
    required: "Required",
    optional: "Optional",
    fullName: "Full name",
    fullNamePlaceholder: "Alex Morgan",
    company: "Company",
    companyPlaceholder: "Company name",
    workEmail: "Work email",
    emailPlaceholder: "alex@company.com",
    jobTitle: "Job title",
    phone: "Phone",
    endpoints: "Approximate number of endpoints",
    passwordManager: "Current password manager",
    identityProvider: "Current SSO or identity provider",
    interests: "What are you most interested in?",
    chooseAny: "Choose any",
    interestLabels: {
      "Passwordless authentication": "Passwordless authentication",
      "KZero Vault": "KZero Vault",
      "MSP partnership": "MSP partnership",
      Demo: "Demo",
      Other: "Other"
    } satisfies Record<(typeof interestChoices)[number], string>,
    comments: "Comments or notes",
    commentsPlaceholder: "Anything you’d like the KZero team to know?",
    demoRequest: "I’d like to book a KZero demo after the conference.",
    demoFollowUp: "The team will contact you to arrange a suitable time.",
    submit: "Send my details",
    submitting: "Saving securely…",
    submitError: "We couldn’t save your details right now.",
    retry: "Your entries are still here—please try again.",
    privacy: "By submitting, you agree that KZero may use these details to follow up about your enquiry. We don’t ask for marketing consent here, and no optional choices are preselected.",
    received: "Details received",
    thankYou: "Thanks for stopping by.",
    confirmation: "The KZero team will follow up after the conference. We’re looking forward to continuing the conversation."
  }
} as const;
